models:
  - backend: onnx
    name: distilbert-base-uncased
    optimization_level: 99
    provider: CPUExecutionProvider
    quantized: false
    type: text
  - backend: onnx
    name: google/vit-base-patch16-224
    optimization_level: 99
    provider: CPUExecutionProvider
    quantized: false
    type: image
